server:
  port: 8080
  address: 0.0.0.0
  ssl:
    key-store: classpath:api.yasyl.com.pfx
    key-store-type: JKS
    key-store-password: ex2hmsjf

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

pagehelper:
  reasonable: false

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sailtotm:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: sailtotm
    # 设置jwt过期时间
    admin-ttl: 720000000000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization
    user-secret-key: sailtotm
    user-ttl: 720000000000
    user-token-name: Authorization
onebound:
  host: api-gw.onebound.cn
  taobao-search: /taobao/item_search
  taobao-search-detail: /taobao/item_get
  key: t8629095275
  secret: 20230825
  scheme: https